### ISSUE TITLE
Update AUTOFOCUS algorithm 

### ISSUE THREAD

**Issue by simonwjackson** [twcapps/vue-spatialnavigation#2]
First, thanks for this!

I've been meaning to write a native vue plugin based on luke-chang/js-spatial-navigation implimentation

My issue is that AUTOFOCUS **up** & **down** focuses the items on the **left** and **right** when `display: inline-block`

Not sure if this helps:
https://github.com/luke-chang/js-spatial-navigation/blob/6732f2b7438a32ea337e67fd5ba7a4df4326645e/spatial_navigation.js#L176

**Comment by bartsidee** [comment]
Hi @simonwjackson, thank you for your feedback.  

We have a strong believe that spatial navigation is part of the UI and user experience and therefore should be designed together with the UX instead of something that comes automatically without clever though behind it. (e.g. with proximity calculations)

With this in mind we actually deliberately not made the AUTOFOCUS feature smart enough to enforce a more manual navigation assignment that has some thought behind it. The main use case for us is to prevent manual assignment of repetitive elements (e.g. tiles in rails or grids). 

The logic is currently indeed based on a relatively simple next/previous sibling detection, which could work for up/down or left/right depending on structure of dom and css.
